version: '3.4'

services:
  wow.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock 
    command: /bin/sh -c "while sleep 1000; do :; done"
  sql:
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "5433:1433"