version: '3.4'

services:
  sql:
    image: microsoft/mssql-server-linux:2017-latest
  redis:
    image: redis
    ports:
      - "6379:6379"
  devenv:
    image: devenv
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - sql
    - redis
 
